### ISSUE TITLE
Ability to register command in crontab with arguments

### ISSUE THREAD

**Issue by paulochf** [jgorset/django-kronos#23]
I found this great package but I missed one thing: passing arguments.

Illustrating with the given example: I could used something like

```python
@kronos.register('0 0 * * *', args={"--arg1": None, "-b": "some-arg2"})
def complain():
    # (...)
```

then the respective crontab entry would be

`0 0 * * * /path/to/python /path/to/manage.py command --arg1 -b=some-arg2 --settings=geoviewer.settings &> /dev/null$KRONOS_BREAD_CRUMB`

Thanks!

**Comment by jgorset** [comment]
Hi @paulochf! That's a cool idea — I'd be happy to accept a pull request that introduces arguments to tasks!

**Comment by paulochf** [comment]
Hey @jgorset,

I wrote some code here, but I don't know how to run the tests. It's my first pull request and Python testing. How do I do it? =)

**Comment by jgorset** [comment]
That's great! More power to you, @paulochf! You can run the tests by executing `./runtests.sh`.

**Comment by paulochf** [comment]
Oh, nice! Didn't look the other files, sorry.

After reading the tests.py file and writing some stuff, I think I need some help yet. I'll tag you on the commit.

**Comment by chayim** [comment]
Any idea when this release will hit PyPi?

**Comment by jgorset** [comment]
@chayim: Right now! It's in v0.7.

**Comment by chayim** [comment]
Thanks! I must have pipped prior to the push.  Can't wait.
