### ISSUE TITLE
pip install failing in Python 3.4

### ISSUE THREAD

**Issue by whusterj** [jgorset/django-kronos#25]
`pip install django-kronos` is failing for me in Python 3.4 with `NameError: name 'execfile' is not defined`. I implemented **[this fix in my fork](https://github.com/whusterj/django-kronos/commit/4f672bd867e1e94b8b78f0f50d3da1be93af84d2)** and have been using that instead.

I've tested this in both 2.7.6 and 3.4.0. Do you see any issue with this fix? If not, would you like a pull request?

Great library. Many thanks.

**Comment by jgorset** [comment]
Thanks @whusterj – and yes, I'd love a pull request. :-)
