### ISSUE TITLE
Django 1.8 warning

### ISSUE THREAD

**Issue by paulochf** [jgorset/django-kronos#29]
I've just tested upgrading to Django 1.8 and got a warning when ran `runserver`.

```
/home/paulo/.virtualenvs/data-279-upd/src/django-kronos/kronos/__init__.py:4: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module
```
Line in question: https://github.com/jgorset/django-kronos/blob/master/kronos/__init__.py#L4

Don't know what it means, but I feel you should know about it.

**Comment by jgorset** [comment]
Thanks for the heads-up, @paulochf! I guess we'll have to fix this before Django 1.9 hits.
