### ISSUE TITLE
Does not work with AppConfig

### ISSUE THREAD

**Issue by davidmoreno** [jgorset/django-kronos#38]
When using AppConfig (https://docs.djangoproject.com/en/1.8/ref/applications/#for-application-authors), kronos does not import the proper cron.py.

As a workaround I import cron from __init__.py, and it works.

A proper fix I guess should use utils.module_loading.autodiscover_modules('cron'). I have a working patch, but not sure. I do separate pull request that does that.

I used AppConfig as I have two modules with the same directory name. It is the django > 1.7 way to allow it.

**Comment by jgorset** [comment]
Fixed in #39.
