### ISSUE TITLE
Pypi package updated?

### ISSUE THREAD

**Issue by paulochf** [jgorset/django-kronos#40]
I guess that the last commits are not packed at Pypi. Is that intentional?

**Comment by topiaruss** [comment]
If not intentional, it's unfortunate. The missing KRONOS_PREFIX in the Cheeseshop just cost me some time.

**Comment by jgorset** [comment]
0.7 should be on Pypi, but I should release 0.8.

**Comment by jgorset** [comment]
0.8 is on Pypi!

**Comment by helenst** [comment]
Thank you for releasing! :-)

**Comment by paulochf** [comment]
Thanks, @jgorset!
