### ISSUE TITLE
Cronjob installed but not called

### ISSUE THREAD

**Issue by LolWalid** [jgorset/django-kronos#41]
Hi,
I'm using django-kronos with MongoDB locally in my computer, I registered tasks using `./manage.py installtasks` i can see them in crontab list and when i run them manually it works fine.

I don't know why tasks are not getting called throw cron.

**Comment by LolWalid** [comment]
It's not working on my MAC but it's working fine on the server. 
I'm closing the issue.

**Comment by escully27** [comment]
This is happening to me but not working on the server. Is there anything you did?

I hope you mean a remote server, too. Thx
