### ISSUE TITLE
sometimes installtasks but tasks cannot run

### ISSUE THREAD

**Issue by daimon99** [jgorset/django-kronos#55]
Django-kronos is a great project.
But a little bug here.
When I install tasks like this:
```
python src/manage.py installtasks
```
then will generate cron like this:
```
*/5 * * * * python /git/turing/manage.py runtask check_sync  --settings=config.local # kronos:3be27dc50a19cd6230f3de732462fa99
```
The right cron etc should be:
```
*/5 * * * * python /git/turing/src/manage.py runtask check_sync  --settings=config.local # kronos:3be27dc50a19cd6230f3de732462fa99
```
The bug is that the path of `manage.py` calculating wrong

**Comment by jgorset** [comment]
Hi @daimon99! You can fix that by either making `src`your working directory or configuring the `KRONOS_MANAGE` environment variable. You'll find more details about that in the README.
