### ISSUE TITLE
Can't install cron tasks

### ISSUE THREAD

**Issue by mmobini** [jgorset/django-kronos#57]
Hi dude,

I've installed django-kronos and kronos packages via pip successfully.

Then I've add 'kronos' to installed_apps of project settings file.

After than, I create a simple cron in this path (/path/to/project/management/commands/task.py) but when i run these commands, it seems it cant find my jobs.

```
python manage.py installtasks
0 tasks installed.
```

```
python manage.py showtasks
* List of tasks registered in Kronos *
>> Kronos tasks
>> Django tasks
```
I also tried adding task.py in root project folder but doesn't work (same as above)

My Django version is 1.8.

Would you please help me?

**Comment by kamyarg** [comment]
the name of the file should be `cron.py` for anyone having the same issue.

**Comment by jgorset** [comment]
Thanks @kamyarg. I'll close this, then.
