### ISSUE TITLE
Change kronos interval (Django Admin)

### ISSUE THREAD

**Issue by jundymek** [jgorset/django-kronos#58]
I have a little problem with call_command in Django. This is my Kronos decorator:

`@kronos.register('*/{} * * * *'.format(config.CRON_MIN))`
In admin.py I have a function which returns new config.CRON_MIN value and runs call_command to reload cron jobs:

```
@receiver(config_updated)
def constance_updated(sender, key, old_value, new_value, **kwargs):
    call_command('installtasks')
    print(key, old_value, new_value)
```
In my terminal window I see:

> 1 tasks removed, 1 installed.
> CRON_MIN 3 4

but when I check it by typing: crontab -l I see cron job with old value of CRON_MIN. When I run installtasks command manually it works as It should (python manage.py installtask). It properly changes interval in kronos cron job. Where I make a mistake? Can you help me?

**Comment by jgorset** [comment]
Sorry for not getting to this a very long time ago. Closing due to old age, but feel free to reopen the issue or make a pull request if you'd still like to fix it.
