### ISSUE TITLE
Only one of two jobs run in a single file

### ISSUE THREAD

**Issue by mdaymond** [jgorset/django-kronos#60]
Hi there - thanks for the great library.   Question . - I have everything setup and registered and it seems to work perfectly to run tasks manually etc.   When I review the cron logs though only two of my tasks are executed.  The only thing I can think of is that I have t

I added the POSTFIX below to try and resolve the issue, but doesn't seem to help

`*/15 * * * * source /opt/python/current/env && /opt/python/run/venv/bin/python /opt/python/bundle/61/app/manage.py runtask subit_vi  --settings=ops.settings # kronos:277d8af879df25a388f98ea0034ca4a3`
`*/20 * * * * source /opt/python/current/env && /opt/python/run/venv/bin/python /opt/python/bundle/61/app/manage.py runtask import_published  --settings=ops.settings # kronos:277d8af879df25a388f98ea0034ca4a3`
`*/30 * * * * source /opt/python/current/env && /opt/python/run/venv/bin/python /opt/python/bundle/61/app/manage.py runtask warm_cache  --settings=ops.settings # kronos:277d8af879df25a388f98ea0034ca4a3`

`@kronos.register('*/20 * * * *')
def import_published():
    import_data(False, 3)

@kronos.register('10,30,50 * * * *')
def subit_vi():
    send_new_video_to_ai(`

I have the following in my settings.
KRONOS_PREFIX = 'source /opt/python/current/env &&'
KRONOS_POSTFIX ='\r\n'

**Comment by jgorset** [comment]
Sorry for not getting to this a very long time ago. Closing due to old age, but feel free to reopen the issue or make a pull request if you'd still like to fix it.
