### ISSUE TITLE
Per server crons?

### ISSUE THREAD

**Issue by csabbey** [jgorset/django-kronos#61]
We run our code on multiple servers, and we want different cron jobs to run on different servers, depending on the server's role. Is there a way to handle this with django-kronos? If not, how about a register function parameter that takes a name from django.conf.settings, and the value of that setting has to be True to register on that server (and default to True if it's missing, for backwards-compatibility)?

**Comment by jgorset** [comment]
Sorry for not getting to this a very long time ago. Closing due to old age, but feel free to reopen the issue or make a pull request if you'd still like to fix it.
