### ISSUE TITLE
Not compatible with pip > 10.0.0

### ISSUE THREAD

**Issue by defgsus** [jgorset/django-kronos#63]
Hi there, 
excellent django utility!

Sadly it breaks with the newest version of pip, because the parse_requirements() function is not longer public.
See, e.g. this answer https://stackoverflow.com/questions/25192794/no-module-named-pip-req#answer-49867265

**Comment by jgorset** [comment]
Thank you! Sorry for not getting to this a very long time ago. Closing due to old age, but feel free to reopen the issue or make a pull request if you'd still like to fix it.
