### ISSUE TITLE
Does it work on Django > 3.2?

### ISSUE THREAD

**Issue by ahmedosama9777** [jgorset/django-kronos#71]
I am not sure, but the using "pip install django-kronos" worked fine, but when I add the kronos into my DJango apps I get a module not found error, but the cron job is working fine! The thing is I am using Daphne to handle websockets, and its status fails with error module not found. I am not sure what to do in such case.

**Comment by jgorset** [comment]
Hi @ahmedosama9777! I am not sure, actually -- I haven't tested it. What's the whole error stack trace, please?

**Comment by ahmedosama9777** [comment]
It works pretty fine on my local environment, but when I use it on my Ubuntu 20.04 deployment server, it somehow crashes Daphne.

**Comment by Muntasir-Mahmud** [comment]
@ahmedosama9777 did it work ?? or did you get another maintained package for cronjobs??

**Comment by ahmedosama9777** [comment]
Currently using Celery
